#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
from geometry_msgs.msg import Twist
from std_msgs.msg import Int32, Bool
import math

class OBS_Control:
    def __init__(self):
        rospy.init_node("control_node")

        rospy.Subscriber("/dist90R", Int32, self.dist90R_CB)
        rospy.Subscriber("/dist45R", Int32, self.dist45R_CB)
        rospy.Subscriber("/dist90L", Int32, self.dist90L_CB)
        rospy.Subscriber("/dist45L", Int32, self.dist45L_CB)
        rospy.Subscriber("/obsR", Bool, self.obsR_CB)
        rospy.Subscriber("/obsL", Bool, self.obsL_CB)
        rospy.Subscriber("/obsC", Bool, self.obsC_CB)

        self.pub = rospy.Publisher("/cmd_vel", Twist, queue_size=1)

        self.cmd_msg = Twist()
        self.obsC = False
        self.obsR = False
        self.obsL = False
        self.dist90R = 0.2
        self.dist90L = 0.2
        self.dist45R = 0.2
        self.dist45L = 0.2
        self.wall_dist = 0.3
        self.kp = 0.05
        self.pre_steer = 0

        self.rate = rospy.Rate(2)

    def dist90R_CB(self, data):
        self.dist90R = data.data / 100.0

    def dist45R_CB(self, data):
        self.dist45R = data.data / 100.0

    def dist90L_CB(self, data):
        self.dist90L = data.data / 100.0

    def dist45L_CB(self, data):
        self.dist45L = data.data / 100.0

    def obsR_CB(self, data):
        self.obsR = data.data

    def obsL_CB(self, data):
        self.obsL = data.data

    def obsC_CB(self, data):
        self.obsC = data.data

    def control(self):
        # 왼쪽과 오른쪽 거리의 평균으로 조향각을 계산
        avg_dist = (self.dist90R + self.dist90L) / 2.0
        value = avg_dist / self.wall_dist

        if value > 1:
            value = 1
        elif value < -1:
            value = -1

        theta = math.acos(value) * 180 / math.pi
        if theta < 15:
            steer = 0
        else:
            steer = (15 - theta) * math.pi / 180 + self.kp * (self.wall_dist - avg_dist)

        # 왼쪽 벽이나 오른쪽 벽 중 하나만 인식되는 경우 반대 방향으로 주행
        if self.obsR and self.obsC and not self.obsL:
            steer = 2
        elif self.obsL and self.obsC and not self.obsR:
            steer = -2
        else:
            speed = 0
            steer = 0

        self.cmd_msg.linear.x = 0.4
        self.cmd_msg.angular.z = steer
        self.pub.publish(self.cmd_msg)
        self.pre_steer = steer

def main():
    OBS_driving = OBS_Control()
    while not rospy.is_shutdown():
        OBS_driving.control()
        OBS_driving.rate.sleep()

if __name__ == "__main__":
    main()



#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import rospy
from sensor_msgs.msg import LaserScan
from std_msgs.msg import Int32, Bool
import math
import statistics

class LaserProcessor:
    def __init__(self):
        rospy.init_node("obs_detect_node")

        rospy.Subscriber("/scan", LaserScan, self.lidar_CB)

        self.pub_dist90_R = rospy.Publisher("/dist90R", Int32, queue_size=1)
        self.pub_dist90_L = rospy.Publisher("/dist90L", Int32, queue_size=1)
        self.pub_dist45_R = rospy.Publisher("/dist45R", Int32, queue_size=1)
        self.pub_dist45_L = rospy.Publisher("/dist45L", Int32, queue_size=1)
        self.pub_obs_R = rospy.Publisher("/obsR", Bool, queue_size=1)
        self.pub_obs_L = rospy.Publisher("/obsL", Bool, queue_size=1)
        self.pub_obs_C = rospy.Publisher("/obsC", Bool, queue_size=1)

        self.laser_msg = None
        self.rate = rospy.Rate(10)
        self.degrees = []
        self.degrees_flag = False

    def lidar_CB(self, msg):
        self.laser_msg = msg

    def process_lidar(self):
        if self.laser_msg is None:
            return

        pub_dist90_R_list = []
        pub_dist90_L_list = []
        pub_dist45_R_list = []
        pub_dist45_L_list = []
        pub_obs_R_list = []
        pub_obs_L_list = []
        pub_obs_C_list = []

        if not self.degrees_flag:
            for i in range(len(self.laser_msg.ranges)):
                angle = (self.laser_msg.angle_min + self.laser_msg.angle_increment * i) * 180 / math.pi
                self.degrees.append(angle)
            self.degrees_flag = True

        for i, n in enumerate(self.laser_msg.ranges):
            x = n * math.cos(self.degrees[i] * math.pi / 180)
            y = n * math.sin(self.degrees[i] * math.pi / 180)

            if 0.15 < y < 0.45 and 0 < x < 0.5:
                pub_obs_R_list.append(n)
            if -0.15 < y < 0.15 and 0 < x < 0.5:
                pub_obs_C_list.append(n)
            if -0.45 < y < -0.15 and 0 < x < 0.5:
                pub_obs_L_list.append(n)

            if 0 < n < 0.5 and -91 < self.degrees[i] < -89:
                pub_dist90_R_list.append(n)
            if 0 < n < 0.5 and -46 < self.degrees[i] < -44:
                pub_dist45_R_list.append(n)
            if 0 < n < 0.5 and 89 < self.degrees[i] < 91:
                pub_dist90_L_list.append(n)
            if 0 < n < 0.5 and 44 < self.degrees[i] < 46:
                pub_dist45_L_list.append(n)

        self.publish_data(pub_dist90_R_list, self.pub_dist90_R)
        self.publish_data(pub_dist45_R_list, self.pub_dist45_R)
        self.publish_data(pub_dist90_L_list, self.pub_dist90_L)
        self.publish_data(pub_dist45_L_list, self.pub_dist45_L)

        self.publish_boolean(pub_obs_R_list, self.pub_obs_R)
        self.publish_boolean(pub_obs_C_list, self.pub_obs_C)
        self.publish_boolean(pub_obs_L_list, self.pub_obs_L)

    def publish_data(self, data_list, publisher):
        if data_list:
            publisher.publish(int(statistics.mean(data_list) * 100))
        else:
            publisher.publish(50)

    def publish_boolean(self, data_list, publisher):
        if len(data_list) > 3:
            publisher.publish(True)
        else:
            publisher.publish(False)

    def run(self):
        while not rospy.is_shutdown():
            self.process_lidar()
            self.rate.sleep()

if __name__ == "__main__":
    processor = LaserProcessor()
    processor.run()
